#!/usr/bin/env bash
case "$1" in
	*.pdf)
		pdftotext $1 -
		;;
	*.zip)
		unzip -l $1
		;;
	*.png|*.jpg|*.jpeg|*.gif)
		img2txt $1
		;;
	*.mkv|*.mp4|*.avi)
		ffprobe $1 -v quiet -print_format json -show_format -show_streams | jq '"Resolution: \(.streams[0].width)x\(.streams[0].height)@Duration: \(.format.duration)"' -r | tr '@' '\n'
		;;
	*)
		bat -n --color always -r :40 $1
		;;
esac
