#!/usr/bin/env bash
source install-utils

# Print header
[[ -a header ]] && color 6 && cat header && color 7 && echo 
echo -e "Linking files...\n"

# Link files
dotlink wallpaper.png ~/Pictures/wallpaper.png
for c in config/* bin xinitrc Xresources xsession zprofile zshenv zshrc aliases functions; do
	dotlink $c ~/.$c 
done
