#!/usr/bin/env bash
dotlink(){
	[[ -a $2 ]] || ln -s $(realpath $1) $2
}
for c in config/*; do
	dotlink $c ~/.$c
done
dotlink i3 ~/.i3
dotlink bin ~/.bin

dotlink xinitrc ~/.xinitrc
dotlink Xresources ~/.Xresources
dotlink xsession ~/.xsession
dotlink zprofile ~/.zprofile
dotlink zshenv ~/.zshenv
dotlink zshrc ~/.zshrc
dotlink aliases ~/.aliases
dotlink functions ~/.functions
