#!/usr/bin/env bash
dotlink(){
	[[ -a $2 ]] || ln -s $(realpath $1) $2 && echo "$2 alerady exists"
}

cat header
echo -e "\nLinking files...\n"

# Link files
for c in config/* i3 bin xinitrc Xresources xsession zprofile zshenv zshrc aliases functions; do
	dotlink $c ~/.$c
done
