#!/usr/bin/bash
symbols_file=~/.data/symbols
symbols="$(cat $symbols_file | dmenu -i -p "symbol:")"
[[ "$symbols" == "" ]] && exit
printf "${symbols:0:1}" | xclip -sel clip
notify-send "copied ${symbols:0:1} to clipboard" -a symbol
