#!/usr/bin/bash
FILE=~/.data/symbols
symbols="$(cat $FILE | dmenu -i)"
[[ "$symbols" == "" ]] && exit
printf "${symbols:0:1}" | xclip -sel clip
notify-send "copied ${symbols:0:1} to clipboard" -a symbol
