#!/usr/bin/env bash
output_grid=~/.tmp/himawari-8
output=~/.tmp/himawari-8-globe.png

date=$(date +%Y/%m/%d)
time=$(date +%H%M00)
time=$[time-time%1000]

url_base="http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/$date/$time"

for x in {0..3}; do
	for y in {0..3}; do 
		url="${url_base}_${x}_${y}.png"
		wget $url -O ${output_grid}-${x}-${y}.png
	done
done

montage $output_grid-[0-3]-[0-3].png -tile 1x4 -geometry +0+0 miff:- | montage - -tile 4x1 -geometry +0+0 $output

rm -f $output_grid-[0-3]-[0-3].png

feh --bg-max $output

