#!/usr/bin/env bash
case "$1" in
lock)
	i3lock
	;;
logout)
	dmenu_confirm "Are you sure you want to logout?"	"i3-msg exit" && vlock -c
	;;
suspend)
	dmenu_confirm "Are you sure you want to suspend?" "systemctl suspend"
	;;
hibernate)
	dmenu_confirm "Are you sure you want to hibernate?" "i3lock"
	systemctl hibernate
	;;
reboot)
	dmenu_confirm "Are you sure you want to reboot?" "systemctl reboot"
	;;
shutdown)
	dmenu_confirm "Are you sure you want to shutdown?" "systemctl poweroff"
	;;
*)
	echo "Usage: i3exit {logout|suspend|hibernate|reboot|shutdown}"
	exit 2
	;;
esac
