#!/usr/bin/env bash
scrot /tmp/screen.png
convert /tmp/screen.png -blur 0x8 -swirl -90 ~/.i3/lock.png -gravity center -composite -matte /tmp/screen.png
echo '{ "command": ["set_property", "pause", true] }' | socat - ~/.tmp/mpvsocket
playerctl pause
sc pause
ponymix mute
i3lock -i /tmp/screen.png
