#!/usr/bin/env bash
IFS=$'\n' 
FILE=~/.config/opener/config
for file in $*; do
	file_opened="false"
	if [[ ! -f "$file" ]]; then
		echo "ERROR: $file not found"
		continue
	fi
	for line in $(< $FILE); do
		if [[ $line =~ ^.*:$ ]]; then
			app=${line::-1}
		else
			regex=$(echo $line | sed -e 's/^[ \t]*//')
			if [[ "$file" =~ $regex ]]; then
				nohup $app "$file" &>/dev/null &
				file_opened="true"
			fi
		fi
	done
	if [[ "$file_opened" == "false" ]]; then
		echo "ERROR: No file association for $file"
	fi
done
