#!/usr/bin/env bash
FILE=~/.promo-time
rm -f $FILE

start=$(date "+%s")
total=$start

for t in $*; do
	unit="${t: -1}"
	time="${t:0:-1}"

	if [[ "$unit" == "m" ]]; then
		time=$((time*60))
	elif [[ "$unit" == "s" ]]; then
		time=$time
	else
		echo "Error: $unit is not a proper unit"
		exit
	fi

	total=$((total+time))
	echo $total >> $FILE
done
