#!/usr/bin/env bash
i3volumefix="pkill -RTMIN+1 i3blocks"
isjack(){
	[[ "$(grep -c "Pin-ctls: 0x00" /proc/asound/card0/codec\#0)" == "2" ]]
}
ismute(){
	[[ "$(awk '/muted/ {print $2}' <(pacmd list-sinks))" == "yes" ]]
}

case "$1" in
"up")
	if [[ "$3"  == "-f" ]]; then
		arg="--allow-boost"
	fi
	pamixer $varg -i "$2" $arg
	$i3volumefix ;;
"down")
	if [[ "$3"  == "-f" ]]; then
		arg="--allow-boost"
	fi
	pamixer $varg -d "$2" $arg
	$i3volumefix ;;
"vol")
	if [[ "$3"  == "-f" ]]; then
		arg="--allow-boost"
	fi
	pamixer $varg --set-volume "$2" $arg
	$i3volumefix ;;
"tmute")
	pamixer -t
	$i3volumefix ;;
"mute")
	pamixer -m
	$i3volumefix ;;
"getvol")
	pamixer --get-volume ;;
"ismute")
	ismute ;;
"isjack")
	isjack ;;
"tplay")
	playerctl play-pause ;;
"pause")
	playerctl pause ;;
"play")
	playerctl play ;;
esac
