#!/usr/bin/env zsh
if [[ "$1" == "" ]]; then
	echo "Usage: $(basename $0) PATTERN [FILE]"
	exit
fi
if [[ "$2" == "" ]]; then
	FILES=
else
	FILES=(${@:2})
fi
PATTERN="$1"
matches=`rg --color always --line-number $PATTERN $FILES`
if [[ "$matches" == "" ]]; then
	echo "No matches found"
	exit
fi
result=$(echo $matches | fzf --ansi)
file=$(echo $result | sed 's/^\([^:]*\):.*/\1/g')
line=$(echo $result | sed 's/^.*:\([0-9]*\):.*/\1/g')
if [[ "$file" == "" ]]; then
	echo "No file selected"
	exit
fi
$EDITOR +$line $file
