#!/usr/bin/env bash
TMP_DIR=~/.tmp
if [[ $# -gt 1 ]] || [[ $# == 1 && -d "$1" ]]; then
	FILE=$(mktemp -u $TMP_DIR/transferXXX.zip)
	zip -r $FILE $*
	trap "{ rm -f $FILE ;}" EXIT
elif [[ $# == 1 ]]; then
	FILE=$1
else
	echo "No files given"
	exit
fi
SIZE=$(stat --printf="%s" $FILE)
TO_UPLOAD=()
if [[ $SIZE -gt 900000000 ]]; then
	SEGMENT=$(mktemp -u $TMP_DIR/transferXXX-)
	trap "{ rm -f $SEGMENT* ;}" EXIT
	split --verbose -b 900m $FILE $SEGMENT
	TO_UPLOAD+=$SEGMENT*
else
	TO_UPLOAD+=("$FILE")
fi
LINKS=()
for f in ${TO_UPLOAD[@]}; do
	BASENAME=$(basename "$f" | sed -e 's/[^a-zA-Z0-9._-]/-/g') 
	LINK=$(curl --progress-bar --upload-file "$f" "https://transfer.sh/$BASENAME")
	LINKS+=("$LINK")
done
printf '%s\n' "${LINKS[@]}"
