#!/usr/bin/env bash
source ~/.api
source ~/.personal
geourl="http://api.ipstack.com/$IP?access_key=${API_IPSTACK}&output=json&legacy=1"
geooutput=$(curl -s $geourl)
lat=$(echo $geooutput | jq ".latitude")
long=$(echo $geooutput | jq ".longitude")
weatherurl="https://api.darksky.net/forecast/$API_DARKSKY/$lat,$long"
weatheroutput=$(curl -s $weatherurl)
temp=$(echo $weatheroutput | jq ".currently | .temperature")
echo $temp | sed 's/\..*//g'
