#!/usr/bin/env bash
[[ -a ~/.personal ]] && source ~/.personal || exit
[[ "$YT_PLAYLIST" == "" ]] && exit

touch ~/.tmp/youtube-songs.{old,new}
youtube-dl -j --flat-playlist $YT_PLAYLIST | jq -r '.id' | awk '{ print "https://youtube.com/watch?v="$0; }' > ~/.tmp/youtube-songs.new
if ! diff -q ~/.tmp/youtube-songs.new ~/.tmp/youtube-songs.old &>> /dev/null ; then
	for song in $(diff ~/.tmp/youtube-songs.old ~/.tmp/youtube-songs.new | grep "^>" | sed 's/^..//g'); do 
		youtube-dl -f 'bestaudio[ext=m4a]' -o "~/Music/%(title)s.%(ext)s" $song
	done
	mv ~/.tmp/youtube-songs.{new,old}
else
	echo "No new songs"
fi
