#!/usr/bin/env bash
song=$(mpc current)
status=$(mpc status | sed -n 2p | sed 's/\[\(.*\)\].*/\1/g')
if [[ "$status" == "playing" ]]; then
	printf "$song\n\n#89DDFF\n"
elif [[ "$status" == "paused" ]]; then
	printf "<span font_style=\"italic\">$song</span>\n\n#959DCB\n"
fi

