#!/usr/bin/env zsh
ran() {
	ps aux | rg $(echo "$1" | sed -e 's/^\(.\)/\[\1\]/')
}

up() {
	cd $(printf '../%.0s' $(seq 1 $1))
}

function $ { 
	"$@"
}

decode(){
	echo $* | base64 --decode | tee >(xclip -sel clip)
}

cl(){
	tmp="$(mktemp)"
	lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
			dir="$(cat "$tmp")"
			rm -f "$tmp"
			if [ -d "$dir" ]; then
					if [ "$dir" != "$(pwd)" ]; then
							cd "$dir"
					fi
			fi
	fi
}

cf(){
	d=$(fd -t d | fzf)
	[[ "$d" != "" ]] && cd $d
}

vf(){
	f=$(fd -t f | fzf)
	[[ "$f" != "" ]] && $EDITOR $f
}

of(){
	f=$(fd -t f | fzf)
	[[ "$f" != "" ]] && $OPENER $f
}
