#!/usr/bin/env zsh
ran() {
	ps aux | rg $(echo "$1" | sed -e 's/^\(.\)/\[\1\]/')
}

up() {
	cd $(printf '../%.0s' $(seq 1 $1))
}

function $ { 
	"$@"
}

decode(){
	echo $* | base64 --decode | tee >(xclip -sel clip)
}

cl(){
	tmp="$(mktemp)"
	lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
			dir="$(cat "$tmp")"
			rm -f "$tmp"
			if [ -d "$dir" ]; then
					if [ "$dir" != "$(pwd)" ]; then
							cd "$dir"
					fi
			fi
	fi
}

cf(){
	#fd -t d --color=always | fzf --ansi | xargs -r cd
	fd -t d --color=auto | sk --ansi | xargs -r cd
}

vf(){
	#fd -t f --color=always | fzf --ansi | xargs -r $EDITOR
	fd -t f --color=auto | sk --ansi | xargs -r $EDITOR
}

sf(){
	#fd . ~/.local/bin ~/.config -E google-chrome -E Code -E GIMP -t f -H -L --color=always | fzf --ansi | xargs -r $EDITOR
	#
	fd . ~/.local/bin ~/.config -E discord -E google-chrome -E "Code - OSS" -E GIMP -t f -H -L --color=auto | sk --ansi | xargs -r $EDITOR
}

of(){
	#fd -t f --color=always | fzf --ansi | xargs -r $OPENER
	fd -t f --color=auto | sk --ansi | xargs -r $OPENER
}
 
tunnel(){
	ssh $1 -L ${2}:localhost:$2
}
