#!/usr/bin/env zsh
export KEYTIMEOUT=1
 
# enable vimode
#bindkey -v

# delete words with backspace
bindkey '^[[3;5~' kill-word
bindkey '^H' backward-kill-word

# make ctrl+l fully clear the terminal rather than just scrolling down
full-clear(){ zle kill-whole-line; printf "\033c"; zle reset-prompt; }
zle -N full-clear 
bindkey '^L' full-clear

# edit current command line contents in $EDITOR
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# use fzf to search history
source /usr/share/fzf/key-bindings.zsh

# remap fzf commands
bindkey '^o' fzf-cd-widget
bindkey '^f' fzf-file-widget

# change cursor shape for different vi modes
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[1 q'
  fi
}
zle -N zle-keymap-select

bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward
